import unittest

class Solution:
    class MinStack:
        def __init__(self):
            pass

        def push(self, val: int) -> None:
            pass

        def pop(self) -> None:
            pass

        def top(self) -> int:
            pass

        def getMin(self) -> int:
            pass

# Generated by ChatGPT
# not verified by a dev
class TestCases(unittest.TestCase):
    def test_case_1(self):
        stack = Solution.MinStack()
        stack.push(-2)
        stack.push(0)
        stack.push(-3)
        self.assertEqual(stack.getMin(), -3)
        stack.pop()
        self.assertEqual(stack.top(), 0)
        self.assertEqual(stack.getMin(), -2)

    def test_case_2(self):
        stack = Solution.MinStack()
        stack.push(1)
        stack.push(2)
        self.assertEqual(stack.getMin(), 1)
        self.assertEqual(stack.top(), 2)
        stack.pop()
        self.assertEqual(stack.top(), 1)
        self.assertEqual(stack.getMin(), 1)

    def test_case_3(self):
        stack = Solution.MinStack()
        stack.push(2)
        stack.push(0)
        stack.push(3)
        stack.push(0)
        self.assertEqual(stack.getMin(), 0)
        stack.pop()
        self.assertEqual(stack.getMin(), 0)
        stack.pop()
        self.assertEqual(stack.getMin(), 0)
        stack.pop()
        self.assertEqual(stack.getMin(), 2)

    def test_case_4(self):
        stack = Solution.MinStack()
        stack.push(0)
        stack.push(1)
        stack.push(0)
        self.assertEqual(stack.getMin(), 0)
        stack.pop()
        self.assertEqual(stack.getMin(), 0)
        stack.pop()
        self.assertEqual(stack.getMin(), 0)

    def test_case_5(self):
        stack = Solution.MinStack()
        stack.push(5)
        stack.push(3)
        stack.push(7)
        self.assertEqual(stack.top(), 7)
        self.assertEqual(stack.getMin(), 3)
        stack.pop()
        self.assertEqual(stack.top(), 3)
        self.assertEqual(stack.getMin(), 3)

if __name__ == "__main__":
    unittest.main()
