class Solution:
	def __init__(self, matrix):
		pass

	def sumRegion(self, row1, col1, row2, col2):
		pass

# Generated by ChatGPT
# not verified by a dev
class TestCases:
	def __init__(self):
		self.run_all_tests()

	def run_all_tests(self):
		self.test_case_1()
		self.test_case_2()
		self.test_case_3()
		self.test_case_4()
		self.test_case_5()

	def test_case_1(self):
		sol = Solution([
			[3, 0, 1, 4, 2],
			[5, 6, 3, 2, 1],
			[1, 2, 0, 1, 5],
			[4, 1, 0, 1, 7],
			[1, 0, 3, 0, 5]
		])
		assert sol.sumRegion(2, 1, 4, 3) == 8

	def test_case_2(self):
		sol = Solution([
			[3, 0, 1, 4, 2],
			[5, 6, 3, 2, 1],
			[1, 2, 0, 1, 5],
			[4, 1, 0, 1, 7],
			[1, 0, 3, 0, 5]
		])
		assert sol.sumRegion(1, 1, 2, 2) == 11

	def test_case_3(self):
		sol = Solution([
			[3, 0, 1, 4, 2],
			[5, 6, 3, 2, 1],
			[1, 2, 0, 1, 5],
			[4, 1, 0, 1, 7],
			[1, 0, 3, 0, 5]
		])
		assert sol.sumRegion(1, 2, 2, 4) == 12

	def test_case_4(self):
		sol = Solution([
			[1]
		])
		assert sol.sumRegion(0, 0, 0, 0) == 1

	def test_case_5(self):
		sol = Solution([
			[2, 0, -3, 4],
			[6, 3, 2, -1],
			[5, 4, 7, 3],
			[2, -6, 8, 1]
		])
		assert sol.sumRegion(1, 1, 2, 2) == 16

if __name__ == "__main__":
	TestCases()
