import unittest

class Solution:
    def calculate(self, s: str) -> int:
        pass

# Generated by ChatGPT
# not verified by a dev
class TestCases(unittest.TestCase):
    def test_case_1(self):
        sol = Solution()
        self.assertEqual(sol.calculate("3+2*2"), 7)

    def test_case_2(self):
        sol = Solution()
        self.assertEqual(sol.calculate(" 3/2 "), 1)

    def test_case_3(self):
        sol = Solution()
        self.assertEqual(sol.calculate(" 3+5 / 2 "), 5)

    def test_case_4(self):
        sol = Solution()
        self.assertEqual(sol.calculate("14-3/2"), 13)

    def test_case_5(self):
        sol = Solution()
        self.assertEqual(sol.calculate("100+200*3-50/2"), 700)

if __name__ == "__main__":
    unittest.main()
